### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by bennewell** [SwiftyJSON/SwiftyJSON#75]
Hi there,

I'm importing SwiftyJSON.swift into my project, but the compiler is flagging up 11 errors - mostly 'Type 'JSON' does not conform to protocol'' for the various LiteralConvertible protocols, and RawRepresentable.

I'm also getting a couple of errors on the line `public init?(rawValue: AnyObject) {` - 'Expected '(' for initializer parameters' and 'Expected declaration'.

**Comment by aadilimperoit** [comment]
I am facing the same issue with xCode 7.3 and Installing SwiftyJSON (3.1.0). Below is the attached screenshot for the same. 
![screen shot 2016-10-05 at 6 27 01 pm](https://cloud.githubusercontent.com/assets/21188912/19114553/1e2fea50-8b2c-11e6-9887-d8efd1db5eb8.png)

**Comment by DavidLari** [comment]
@aadilimperoit Did you see in the read me that the requirement for 3.1 is for Xcode 8? If you still must use 7.3, you need an older version of SwiftyJSON.

**Comment by WilsonCP** [comment]
@DavidLari Hi, I also have the same issue. Do you have any idea what version of SwiftyJSON would work with xcode 7.3?

**Comment by DavidLari** [comment]
Looks like I have 2.3.3 in my 7.3 project.

**Comment by zhigang1992** [comment]
You can use version `2.4.0` for support prior to Swift3.
