### ISSUE TITLE
SwitfyJSON breaks with update to iOS 8.3 & Xcode 6.3

### ISSUE THREAD

**Issue by slysid** [SwiftyJSON/SwiftyJSON#200]
Hi,

I am developing an app in Swift and I have ported SwitfyJSON and it worked fine in iOS 8.2. Once I upgraded my iOS to 8.3 and Xcode to 6.3, I got lot of compile errors in Swifty and most of them are warnings to change "as" with "as?" optional. There was one error in function rawString which complained "NSString? is not convertible to String?"

I have modified the code from 

return NSString(data: data, encoding: encoding)

 to 

return NSString(data: data, encoding: encoding) as? String

Then the code compiled successfully but all data retrieval statements are not working now.For example,
response["myname"] returned the value in 8.2 but the same line returning null in 8.3 after fixing compilation errors

**Comment by macu** [comment]
I notice there's a branch called xcode6.3 -- could be tested against the final Xcode release, and then merged back to master. Will keep an eye on this issue for updates.

**Comment by zacharyclaysmith** [comment]
This is a pretty major issue...is anyone actively working on this?

**Comment by teliaz** [comment]
Wish I didn't update to latest version ... now i have to wait until a stable release
:(

**Comment by paulhyunkim** [comment]
same here. does anyone know a way to rollback to swift 1.1 on xcode 6.3?

**Comment by das3in** [comment]
Most of the autofixes in XCode work and retain SwiftyJSON functionality. most just find and replacing "as" with "as!"

NSString not actually being a String anymore seems problematic. I force downcasted it... but I'm not sure that's the best solution.

**Comment by brentkirkland** [comment]
:(

**Comment by webbersky** [comment]
I edited the code, fixing the as! and NSString issue, new to github, wasn't sure how to paste the code so i've put it up on pastebin
http://pastebin.com/k8ehqwwH
Hope this helps (:

**Comment by slysid** [comment]
I tried the same fix and the code gets compiled successfully but the values are not retrieved from JSON. Are you able to retrieve the value?

**Comment by chrux** [comment]
Any plans to publish an update with this?

**Comment by rcgary** [comment]
You guys can use `xcode6.3 ` brunch for now. It works fine on my side. Happy to see this branch merge into master soon

**Comment by rguldener** [comment]
For the copy paste lovers (like me), here is the pod entry for the xcode6.3 branch:

`pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'`

**Comment by nunogoncalves** [comment]
I'm using the xcode6.3 branch and haven't noticed anything different. Still, next time, I'll give it more time until I update to the latest versions os swift. Specially if the language features are not backwards compatible.. Yesterday was update and fix broken code all day long.

**Comment by josephkandi** [comment]
The xcode 6.3 branch works with some minor fixes on as!. Just Xcode suggestions and everything will be fine.

**Comment by slysid** [comment]
Xcode 6.3 branch compiled with our any error for me but subscript with valid key is nor working for me. for example,

var temp = JSON({"unit:kms"}())
        
 println(temp["unit"])

prints null

**Comment by kamoljan** [comment]
+1

**Comment by DingSoung** [comment]
升了6.3后  碰到问题了     Alamofire 1.2已经OK   大大快加油

**Comment by Jan0707** [comment]
I can reproduce @slysid error here !

+1

**Comment by Jan0707** [comment]
Oddly though, some requests work just fine, while others won't. It's completely reproducible.

**Comment by Jan0707** [comment]
When extending the code snippet like this:

        let json = JSON({"unit:kms"}())
        if let unit = json["unit"].string {
            println(unit)
        } else {
            println(json["unit"].error)
        }

We receive the following error:

        Optional(Error Domain=SwiftyJSONErrorDomain Code=901 "Dictionary["unit"] failure, It is not an        
        dictionary" UserInfo=0x7fa86a245d50 {NSLocalizedDescription=Dictionary["unit"] failure, It is not an 
        dictionary})

**Comment by chschu** [comment]
There seems to be an issue with the subscript operator in Swift 1.2, it returns `nil` when a Swift dictionary is converted to `AnyObject`, which is what SwiftyJSON does here.

The following snippet prints `nil`, not `Optional("World")`:
```
let obj: AnyObject = ["Hello":"World"]
println(obj["Hello"])
```
I already reported a bug to Apple.

Pull request follows.

**Comment by chschu** [comment]
The error seems to occur only if there is an "import SpriteKit" somewhere in the project.

**Comment by chschu** [comment]
@slysid, @Jan0707: `JSON({"unit:kms"}())`, is basically the same as `JSON("unit:kms")`. It just creates a a `JSON` instance representing the string `"unit:kms"`. To create a `JSON` instance representing a dictionary, you need to pass a Swift dictionary to the initializer, e.g. `JSON(["unit" : "kms"])`. To parse a string into a `JSON` instance, you could use something like that (quite ugly because the quotes need to be escaped):
```
JSON(data: "{\"unit\":\"kms\"}".dataUsingEncoding(NSUTF8StringEncoding)!)
```

**Comment by hammyhamza** [comment]
The platform of the target `Pods` (iOS 7.1) is not compatible with `SwiftyJSON (2.1.3)` which has a minimum requirement of OS X 10.9 - iOS 8.0.

**Comment by paul999** [comment]
I am seeing some serious backwards compatablity issues with the 6.3 branch. Besides that I now everywhere need to use .string instead of .stringValue (And other types as well), it simply breaks when the datatype in JSON is different from the type you asks. I just spent nearly a day fixing most of my app because I assumed certain conversions in the app happen by SwiftyJson (And in the past it did that correctly).

**Comment by Jan0707** [comment]
@chschu I do not import SpriteKit anywhere in my project but the sample code still fails

**Comment by adooylabs** [comment]
I'm having the same problem.

**Comment by whusted** [comment]
Do we have a consensus short-term solution to this problem?

**Comment by adooylabs** [comment]
this works for me https://github.com/SwiftyJSON/SwiftyJSON/pull/199

**Comment by whusted** [comment]
@adooylabs Thank you!

**Comment by ejpusa** [comment]
Down to one update bug. Seems like a tough one. Have had no luck if a second set of eyes can take a look at it.  Thanks
![screen shot 2015-04-11 at 7 18 37 pm](https://cloud.githubusercontent.com/assets/1279819/7103688/fd7b7adc-e081-11e4-95f2-ab5d188f26f2.png)

**Comment by ejpusa** [comment]
Ok, this Pod line seems to fix all: pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'

**Comment by Jan0707** [comment]
@ejpusa In Swift 1.2 NSString does not equal String and therefore violates the functions return policy.

You can simply convert it though, have a look at this playground example:

    //: Playground - noun: a place where people can play

    import UIKit

    func returnString() -> String {
        return NSString(string: "Test") as String
    }  

    println(returnString())

**Comment by andrewfashion** [comment]
Did this solution work for anyone?

Ok, this Pod line seems to fix all: pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'

**Comment by rlam3** [comment]
This is breaking with Alamofire as well. Anybody have the same issue?

**Comment by franksauvag** [comment]
I tried the xcode 6.3 branch, it compiles, but I am getting the following error while trying to get an Array now.

Eg with the following Json:
{
"frames": [
   {"x":2,"y":2,"w":49,"h":49 }, 
   {"x":53,"y":2,"w":49,"h":49 }, 
   {"x":104,"y":2,"w":49,"h":49 }, 
   {"x":155,"y":2,"w":49,"h":49 }, 
   {"x":206,"y":2,"w":49,"h":49 }, 
   {"x":257,"y":2,"w":49,"h":49 }, 
   {"x":308,"y":2,"w":49,"h":49 }, 
   {"x":308,"y":2,"w":49,"h":49 }
 ],
"meta": {
    "version": "1.0",
    "image": "explosion1.png",
    "size": {"w":359,"h":53 }
 }
}


When calling:
let frames = json["frames"]

frames is an empty array where it was containing all the frames in the past..

digging to understand, but if someone know why, this might be great

**Comment by Jan0707** [comment]
I still get the following error:

`Optional(Error Domain=SwiftyJSONErrorDomain Code=901 "Dictionary["_links"] failure, It is not an dictionary" UserInfo=0x7fce64c0b820 {NSLocalizedDescription=Dictionary["_links"] failure, It is not an dictionary})`

When trying:

`        let json = JSON(data:data)
        if let previousEpisodeUrl = json["_links"]["previousepisode"]["href"].URL {
            println(previousEpisodeUrl.URLString)
        } else {
            println(json["_links"]["previousepisode"]["href"].error)
        }`

You can see the JSON I am receiving here: [http://api.tvmaze.com/shows/4?embed=previousepisode](http://api.tvmaze.com/shows/4?embed=previousepisode)

This used to work before, as the code already is half a year old. Did I miss any breaking changes or is this an bug on SwiftyJSON's side ?

**Comment by slysid** [comment]
Fix works for me. All my SwitfyJSON functionalities in my project are working fine.

**Comment by franksauvag** [comment]
Thanks, everything is back to normal with the latest master :) :+1:

**Comment by chschu** [comment]
@Jan0707: After removing the `.URLString` from your code, it compiles and prints `http://api.tvmaze.com/episodes/144440`. Which iOS SDK do you use?

**Comment by Jan0707** [comment]
@chschu My `Base SDK` is set to `Latest iOS (iOS 8.3)` and it still throws that error here. It might be worth mentioning that I do not include SwiftyJSON via Cocoapods but rather copy the Swift file manually ( which I of course took from the latest master).

**Comment by Litome** [comment]
Similar problem here.
There is a radar logged in on this issue: http://openradar.appspot.com/20489846
With iOS 8.3 Submitting an HTTP POST request with Content-type of application/json will still send as application/x-www-form-urlencoded

**Comment by chschu** [comment]
@Jan0707 Strange, that's exactly how I do it. Maybe you could create a minimal example (Code Snippet including a small JSON string) that fails and put it into a Gist?

**Comment by Jan0707** [comment]
@chschu Oddly enough, this gist works perfectly fine:

https://gist.github.com/Jan0707/cc8db99778c0f527bef5

There must be something wrong in my project - especially since some of my request work while others won't.

**Comment by Jan0707** [comment]
I can also post my whole project if that is any help ?

**Comment by Jan0707** [comment]
Finally got it ! Apparently there were some changes in the `stringValue` . Sorry for the inconvenience !
