### ISSUE TITLE
Xcode 12 Workaround

### ISSUE THREAD

**Issue by tattn** [SwiftyJSON/SwiftyJSON#1066]
I use Carthage to build SwiftyJSON.
But it was failed in Xcode 12 beta 1.

Show the following error:
```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in SwiftyJSON.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It can be also reproduced on archive build.

So I added the workaround for Xcode 12.
Please try the following if you use Carthage:

```ruby
github "tattn/Alamofire" "hotfix-xcode12"
```

The change is https://github.com/SwiftyJSON/SwiftyJSON/compare/master...tattn:hotfix-xcode12?expand=1.

**Comment by sjorsvb** [comment]
For CocoaPods you can temporarily use
`pod 'SwiftyJSON', :git => 'https://github.com/tattn/SwiftyJSON.git', :branch => 'hotfix-xcode12'`

**Comment by ethancwb** [comment]
Looks like it is still broken in Xcode beta 2. 😢

**Comment by felginep** [comment]
This is fixed on beta 4

**Comment by netgfx** [comment]
It throws No such module 'SwiftyJSON' I'm using: `pod 'SwiftyJSON', '~> 5.0'`
Any ideas?

**Comment by mido89** [comment]
No such module 'SwiftyJSON' in Xcode 12 Any help ?

**Comment by Ariandr** [comment]
Here is the workaround for Xcode 12:
https://medium.com/@khushwanttanwar/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9

**Comment by BansCons** [comment]
This fix won't work on Xcode 12.2. SwiftyJSON is still throwing 'no such module'

**Comment by ZhannySunny** [comment]
> This fix won't work on Xcode 12.2. SwiftyJSON is still throwing 'no such module'

Did you fix this issue?
